//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniHostel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdvancedService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvancedService()
        {
            this.BillAdvancedServiceDetails = new HashSet<BillAdvancedServiceDetail>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }

        [Range(1, 100000, ErrorMessage = "Price must be greater than 0")]
        public float Price { get; set; }

        public string Unit { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string HostID { get; set; }
    
        public virtual Host Host { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillAdvancedServiceDetail> BillAdvancedServiceDetails { get; set; }
    }
}
