//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniHostel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillAdvancedServiceDetails = new HashSet<BillAdvancedServiceDetail>();
            this.BillCompulsoryServiceDetails = new HashSet<BillCompulsoryServiceDetail>();
        }
    
        public string ID { get; set; }
        public System.DateTime Time { get; set; }

        [Range(1, float.MaxValue, ErrorMessage = "The fee could not be negative")]
        public Nullable<float> OtherFee { get; set; }

        [Range(1, float.MaxValue, ErrorMessage = "Total is not a valid number (It must be greater than 0)")]
        public float Total { get; set; }

        public Nullable<bool> isPaid { get; set; }
        public string Description { get; set; }
        public string RoomID { get; set; }
        public string RenterID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillAdvancedServiceDetail> BillAdvancedServiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillCompulsoryServiceDetail> BillCompulsoryServiceDetails { get; set; }
        public virtual Room Room { get; set; }
        public virtual Renter Renter { get; set; }
    }
}
