//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniHostel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BillAdvancedServiceDetail
    {
        public int ID { get; set; }
        public string AdvancedServiceID { get; set; }
        public string BillID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Please enter a valid quantity")]
        public int Quantity { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "The amount is not valid")]
        public int Amount { get; set; }
        public string Description { get; set; }
    
        public virtual AdvancedService AdvancedService { get; set; }
        public virtual Bill Bill { get; set; }
    }
}
