//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> isActive { get; set; }
        public int RoleID { get; set; }
    
        public virtual Host Host { get; set; }
        public virtual Renter Renter { get; set; }
        public virtual Role Role { get; set; }
    }
}
